package com.tiagorsnp.ifrsdev1appv1r1;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;

@RestController // This means that this class is a Controller
@RequestMapping(path="/pessoa") // This means URL's start with /demo (after Application path)

public class PessoaController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    private com.tiagorsnp.ifrsdev1appv1r1.PessoaRepository repository;


    @PostMapping(
            value = "incluir"
            ,consumes = {MediaType.APPLICATION_JSON_VALUE}
            ,produces = {MediaType.APPLICATION_JSON_VALUE}
    ) // Map ONLY POST Requests
    
    public @ResponseBody com.tiagorsnp.ifrsdev1appv1r1.Pessoa Incluir (@RequestBody  com.tiagorsnp.ifrsdev1appv1r1.Pessoa entidade) {
        
    	// @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        repository.save(entidade);

        return entidade;
    }

}